TILT_MAGNITUDE_YELLOW = 2.0
TILT_MAGNITUDE_ORANGE = 5.0
TILT_MAGNITUDE_RED = 10.0

TILT_RATE_YELLOW = 0.5
TILT_RATE_ORANGE = 1.5
TILT_RATE_RED = 3.0

DISPLACEMENT_MM_YELLOW = 10.0
DISPLACEMENT_MM_ORANGE = 25.0
DISPLACEMENT_MM_RED = 50.0

DISPLACEMENT_RATE_YELLOW = 2.0
DISPLACEMENT_RATE_ORANGE = 5.0
DISPLACEMENT_RATE_RED = 10.0

CRACK_WIDTH_MM_YELLOW = 2.0
CRACK_WIDTH_MM_ORANGE = 5.0
CRACK_WIDTH_MM_RED = 10.0

CRACK_GROWTH_RATE_YELLOW = 0.5
CRACK_GROWTH_RATE_ORANGE = 1.5
CRACK_GROWTH_RATE_RED = 3.0

VIBRATION_ENERGY_BASELINE_MULTIPLIER_YELLOW = 3.0
VIBRATION_ENERGY_BASELINE_MULTIPLIER_ORANGE = 6.0
VIBRATION_ENERGY_BASELINE_MULTIPLIER_RED = 10.0

CRACK_DETECTED_MIN_LEVEL = "ORANGE"

PERSISTENCE_READINGS_YELLOW = 2
PERSISTENCE_READINGS_ORANGE = 3
PERSISTENCE_READINGS_RED = 1

PERSISTENCE_SECONDS_YELLOW = 60
PERSISTENCE_SECONDS_ORANGE = 90
PERSISTENCE_SECONDS_RED = 0

DEESCALATION_PERSISTENCE_MULTIPLIER = 2

STALE_READING_INTERVAL_MULTIPLIER = 3

DATA_QUALITY_SCORE_GREY_THRESHOLD = 0.3
DATA_QUALITY_SCORE_GOOD_THRESHOLD = 0.7
DATA_QUALITY_SCORE_FAIR_THRESHOLD = 0.3

SENSOR_STATUS_OFFLINE_VALUES = ("offline", "fault")

CALIBRATION_STATUS_UNCALIBRATED = "uncalibrated"

NEIGHBOR_AGREEMENT_MIN_COUNT = 2

RISK_LEVELS_ORDER = ("GREEN", "YELLOW", "ORANGE", "RED")

RISK_LEVEL_GREY = "GREY"

DATA_QUALITY_STATUS_GOOD = "good"
DATA_QUALITY_STATUS_FAIR = "fair"
DATA_QUALITY_STATUS_POOR = "poor"

SENSOR_HEALTH_HEALTHY = "healthy"
SENSOR_HEALTH_DEGRADED = "degraded"
SENSOR_HEALTH_OFFLINE = "offline"
SENSOR_HEALTH_UNCALIBRATED = "uncalibrated"

RULE_TRIGGERED_UNCONFIRMED_SINGLE_SENSOR = "unconfirmed_single_sensor"
RULE_TRIGGERED_SENSOR_OFFLINE = "sensor_offline"
RULE_TRIGGERED_SENSOR_STALE = "sensor_stale"
RULE_TRIGGERED_LOW_DATA_QUALITY = "low_data_quality"
RULE_TRIGGERED_UNCALIBRATED_ELEVATED = "uncalibrated_elevated"
RULE_TRIGGERED_NORMAL = "normal"

RECOMMENDED_ACTION_GREEN = "No action required. Continue routine monitoring."
RECOMMENDED_ACTION_YELLOW = "Monitor closely. Review trend over next reading cycle."
RECOMMENDED_ACTION_ORANGE = "Elevated risk detected. Verify with field team if trend continues."
RECOMMENDED_ACTION_RED = "Critical risk indicators present. Immediate field verification recommended."
RECOMMENDED_ACTION_GREY = "Sensor data unavailable or unreliable. Verify sensor status before relying on this node."
